version: 2.1

orbs:
  architect: giantswarm/architect@0.8.4

workflows:
  test:
    jobs:
      - architect/go-build
          name: go-build
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/integration-test:
          name: integration-test-basic
          test-dir: "integration/test/basic"
          requires:
            - go-build

      # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker-legacy:
          name: push-certctl-to-aliyun-master
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/certctl"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master

      - deploy:
          filters:
            branches:
              only: master
          requires:
          - integration-test-basic
