version: 2.1

orbs:
  architect: giantswarm/architect@0.8.4

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: certctl
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/integration-test:
          name: integration-test-basic
          test-dir: "integration/test/basic"
          requires:
            - go-build

      - architect/push-to-docker:
          name: push-certctl-to-quay-master
          image: "quay.io/giantswarm/aws-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master

      - architect/push-to-docker:
          name: push-certctl-to-aliyun-master
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/certctl"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master
