version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: certctl
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/integration-test:
          name: integration-test-basic
          kind-config: "integration/test/basic/kind-config.yaml"
          install-app-platform: true
          test-dir: "integration/test/basic"
          requires:
            - go-build

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            branches:
              only: master

